name: quizzle
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get: ^4.6.5
  logger: ^2.5.0
  easy_separator: ^1.0.1
#  blurhash_flutter:
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_zoom_drawer: ^3.2.0
  liquid_pull_to_refresh: ^3.0.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.3

  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  firebase_storage: ^12.3.6
  

  flutter_local_notifications: ^18.0.1
  path_provider: ^2.0.8
  http: ^1.2.2
  url_launcher: ^6.0.18
  animate_do: ^3.3.4
  iconsax: ^0.0.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/DB/papers/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: AppIcons
    fonts:
      - asset: assets/icons/AppIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#7424ed"
  color_dark: "#5d0ed2"
  android_gravity: center
  fullscreen: true
  image: assets/images/app_splash_logo.png